### ISSUE TITLE
Rename Exception class so it does not conflict

### ISSUE THREAD

**Issue by andy1547** [calcinai/xero-php#148]
PHP Fatal error:  Cannot use XeroPHP\Exception as Exception because the name is already in use in /var/www/portal/vendor/calcinai/xero-php/src/XeroPHP/Remote/Query.php on line 6
I'm using this in Laravel 5.1, so I'm guessing there's a conflicting class somewhere.
Giving an alias to the exception in the Query class fixed my issue...

**Comment by calcinai** [comment]
Ha, I wonder how this wasn't found earlier.  Can you please submit a PR? I'm about to start on the 2.0 branch and will make sure this isn't an issue moving forward.

**Comment by andy1547** [comment]
I've submitted a PR

**Comment by calcinai** [comment]
Just looking through this.. What do you think the possibility of people trying to catch one of these exceptions already are and this introducing breaking changes?

**Comment by andy1547** [comment]
Very likely, probably best to pull it when 1.3 is released.

**Comment by coop182** [comment]
Hey @calcinai we are running into this as well... whats the latest on it?

**Comment by calcinai** [comment]
Hey, so I've created a branch and PR (#158) to address this.  I think the cause was just that there was an Exception defined in the NS where it was being aliased.  I don't think it's anything specific to Symfony/Laravel.

I have made the change that I think will fix it without having to actually change exception names (for BC) but will throw slightly different exceptions.  This should not be an issue either since they still extend the original one, so if people are bothering to catch specifics, it should still be equivalent.

**Comment by calcinai** [comment]
(this is a stop-gap for 2.0, which I have finally started work on!)

**Comment by calcinai** [comment]
How are you all getting on with this patch?

**Comment by andy1547** [comment]
I can confirm your solution has solved the root cause of issue I was having and I don't see the need for any breaking changes... yes ideally the Exception class would be named Xero Exception (I've submitted PR for 2.0 for this).
