### ISSUE TITLE
Item creation bug- InventoryAssetAccountCode is not mandatory for untracked items

### ISSUE THREAD

**Issue by andy1547** [calcinai/xero-php#149]
I'll get a pull request submitted asap

**Comment by nathangoss** [comment]
Did this get resolved? Happy to help if required

**Comment by andy1547** [comment]
I can confirm this is still an issue.
Unfortunately I've been pushed for time lately to try and modify the scrubbing process.
The problem is this field is conditionally required,  but I'm guessing that'd be difficult to scrub.
Any thoughts anyone?

**Comment by AlexBlake** [comment]
@calcinai, Just came across this issue still being present. Any thumb suck estimates on when this might be resolved? Using a workaround for now, but not an optimal solution. 
Been looking at how to even get this kind of information via the generator, seems a bit obscure since there's no direct references to required fields in the docs. If you can get that info, then it should just be a case of pushing an almost 'required_if' sub array of field names to the property arrays on models, then implementing that in validation on request, thoughts? 
Will keep looking for a solution and do a pull request if i can get somewhere productive with generating that info from the docs.

**Comment by calcinai** [comment]
Have you seen the [new generator and swagger specs](https://github.com/calcinai/xero-schemas)? You can make a manual workaround in the bottom of the generator for now, and then 2.0 of this lib builds from that. I mentioned in another issue that I'm currently texting and then I'll get a few of you guys to test too. 

That said, 2.0 will be the end of this major of code/generator, so it probably won't matter if there are a couple of things hardcoded in there..
