### ISSUE TITLE
Saving contacts to a group?

### ISSUE THREAD

**Issue by wilr** [calcinai/xero-php#16]
According to the API docs a PUT request to /ContactGroups/ContactGroupID/Contacts is required. Can't see anywhere where this would be possible using the existing API. Happy to implement but just wondering if I've missed something

**Comment by calcinai** [comment]
Are you wanting to add contacts to an existing ContactGroup?  If so, something like this may work:

```
$contact = new XeroPHP\Models\Accounting\Contact();
$contact->setName('Test Contact');
$xero->save($contact);


$contact_group = $xero->load('Accounting\\ContactGroup')->where('Name', 'Test Group')->execute();
$contact_group->addContact($contact);
$xero->save($contact_group);
```

I'm not sure the API allows you create a new contact at this endpoint, so you'll be making two calls to the API.  If you were creating multiple contacts, you could look at the batch saving #7 feature.

Hopefully I haven't completely missed the question!

**Comment by wilr** [comment]
Had hoped that worked, it's what I originally coded but I get the following exception

> A Contact Group already exists with this name

**Comment by calcinai** [comment]
I see what you mean - I missed that it was actually a different URL.  I'll have a think about a nice way to implement this, probably just being able to wrap a custom request like so:

```PHP
$url = new URL($xero, sprintf('%s/%s/Contacts', $contact_group::getResourceURI(), $contact_group->getGUID()));
$request = new Request($xero, $url, Request::METHOD_PUT);

$data = array($contact::getRootNodeName() => $contact->toStringArray());

$request->setBody(\XeroPHP\Helpers::arrayToXML($data));
$request->send();
```

The above good worked for me instead of the ```->save()``` calls.  On a side note, you've made me find a bug that was semi-related, so pull the latest copy if that doesn't work for you.

**Comment by wilr** [comment]
@calcinai Will test tonight. Thanks!

**Comment by calcinai** [comment]
@wilr - did this end up working for you?

**Comment by Alphonseabraham** [comment]
Hi calcinai, 

```
$contactgroup = $xero->loadByGUID('Accounting\\ContactGroup', $contactGroupId)->save();
```
Can you look into this? This commit to set a contact group to a contact is not working. It keeps saying archive contact cannot be grouped. However, if we used your code below to set contactgroup its working.

```
$url = new URL($xero, sprintf('%s/%s/Contacts', $contactgroup::getResourceURI(), $contactgroup->getGUID()));
$request = new Request($xero, $url, Request::METHOD_PUT);
$data = array($contact::getRootNodeName() => $contact->toStringArray());
$request->setBody(\XeroPHP\Helpers::arrayToXML($data));
$request->send(); 
```

Thanks,
Alphonse

**Comment by calcinai** [comment]
@Alphonseabraham Are you sure you're not creating a new contact in the second block of code?

**Comment by Alphonseabraham** [comment]
@calcinai ,

This is my code for getting the contact to add a contact group. I have commented the setName code because I think it was trying to create another contact with the same details which prompted me with the error "Unable to assign an Archived contact". Is there any way we can update the customer contact if they want to update their name.

```
$contact->setContactID($contactData[0]['ContactID'])
      //->setName('Guadalupe Farmer')
        ->setFirstName('Jill')
        ->setLastName('Conner')
        ->save();
```

Thanks,
Alphonse
