### ISSUE TITLE
Fatal error / Resource Not Found in Error when trying to load contact addresses

### ISSUE THREAD

**Issue by benjaminschneider1994** [calcinai/xero-php#397]
Hello

I am trying to load contact addresses using the code directly below but i am getting the error below.

$addresses = $xero->load(Accounting\Address::class)->execute();

Fatal error: Uncaught XeroPHP\Remote\Exception\NotFoundException: Resource Not Found in

Thanks

**Comment by benjaminschneider1994** [comment]
I have looked at the examples but cannot find anything that helps, it appears address is the only one that I cannot get to work. If this isnt the right place to ask questions on how to use it, please tell me where is.

**Comment by calcinai** [comment]
Have a look at [the developer docs](https://developer.xero.com/documentation/api/api-overview) to see if what you're trying to do is possible.

**Comment by wiki99** [comment]
i got same issue and unable to find it in developer docs unable to fetch address because account/Address return null an empty object for Address and Phone both  

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
ini_set('display_errors',1);
require 'vendor/autoload.php';
$xero = new \XeroPHP\Application\PrivateApplication($config);
	
echo "<pre>";
$contacts =$xero->load('Accounting\\Contact')->execute();

foreach($contacts as $contact)
{

	$add=$xero->load(Address::class)->execute();
	print_r($contact->getAddresses($add->getAddressLine1()->$add->getCity()));
		
}
