### ISSUE TITLE
LineItem loadbyGUID resource not found

### ISSUE THREAD

**Issue by stevezaxz** [calcinai/xero-php#401]
Hi,

I have an issue when loading a LineItem class it doesn't seem to load the class property it just return a resource not found exception.

	$xero = new PrivateApplication($this->xero_config);
        $xero->loadByGUID(LineItem::class, '4a1a0e90-481e-4bbe-9786-3fad3cf55674');

	 echo "<pre>";echo print_r($line_item,true);

I cannot proceed in updating/deleting invoice lineitems because of this issue.

Do we have a workaround for this?

Thank you

**Comment by calcinai** [comment]
@stevezaxz I don't think it's possible to load a `LineItem` directly.  It comes in a collection as part of an `Invoice`.  If you remove them from that collection and save, they will be deleted (not sure exactly what's happening at Xero's end).

**Comment by FrankEBailey** [comment]
The workaround I've found is to instantiate the $Invoice, then do
    $Invoice->LineItems->RemoveAll();
so that the existing line items are removed, then do
    $Invoice->save();
and thereafter add the updated line items. 

This approach is actually very clean and requires the least cruft and is also the only approach I've found that avoids needing to store LineItemIDs in my database.
