### ISSUE TITLE
Save on invoice does not return invoice object

### ISSUE THREAD

**Issue by Chris-Pratt-Clystnet** [calcinai/xero-php#432]
Currently I am saving an invoice and being returned a response object with an elements array in it that contains the created invoice in array format.

Now if I call save on an object I would expect it to go away and save the object and then return the object back with the updated fields. That behaviour is exactly what happens when you call save on a contact.

So is this a bug or am I missing something?

**Comment by DivineOmega** [comment]
I'd also prefer this behaviour, rather it just returning a response object.

**Comment by timacdonald** [comment]
The package mutates the original invoice object when you call `save()`. So when you call save it will update the model you already have in the variable.

Although I don't disagree with you - I do also find it handy to be able to get the response when debugging issues and I think if the package completely hide the ability to get the response it would make things a lot harder because now there is no way to see the payload.

I think the issue is that you can call `save()` on the HTTP client (the `Application` class) and `save()` on the model, so what should be returned feels like it should be different in both places. I would think the best behaviour is for the HTTP client to return a response and the model to return itself.

```php
$response = $xero->save($invoice);

$invoice = $invoice->setApplication($xero)->save();
```

The problem with this is that now you assume that the original invoice isn't mutated if you just called...

```php
$invoice->setApplication($xero)->save();
```

but it is. Anyway, that is my 2 cents on the issue :)

**Comment by Chris-Pratt-Clystnet** [comment]
Yes i can see why both cases are useful  and I would say a middle ground would be good then.

So still return the response but add a method to the response that will parse the response into the original object.

For now I have been using the following code to parse the object for any one who hasn't worked this out.

```php
$invoiceData = $invoice->save()->getElements()[0];
$invoice->fromStringArray($invoiceData, true);
````
