### ISSUE TITLE
Signature method invalid

### ISSUE THREAD

**Issue by aamirshakil** [calcinai/xero-php#565]
I am using the below function on a button click for the request token but it shows invalid signature error..

function test_authorize(){
	
	var consumer_key = document.getElementById('consumer_key').value;
	var consumer_secret = document.getElementById('consumer_secret').value;
	var url = "https://api.xero.com/oauth/RequestToken?";
	var dataString = "oauth_consumer_key="+consumer_key
						+"&oauth_consumer_secret="+consumer_secret
						+"&oauth_signature_method=HMAC-SHA1"
						+"&oauth_nonce=1556117987"
						+"&oauth_timestamp=1556117987"
						+"&oauth_version=1.0";
						
window.open(url+dataString, "_blank", "height=540,width=440,left=450,top=150");
	}

**Comment by timacdonald** [comment]
This issue is not related to this package. This package is a PHP wrapper around the Xero API. You'll need to consult the Xero API docs for help.

https://developer.xero.com/documentation/

...and just a side note - I *really* wouldn't expose your keys publicly via HTML / Javascript, otherwise I can just copy them from your site and start sending invoices / refunds etc from your account 👀
