### ISSUE TITLE
Throw exception if page is used with model that doesn't support it

### ISSUE THREAD

**Issue by mhlavac** [calcinai/xero-php#58]
It would awesome if we can throw an exception in case you use page filter for models that doesn't support it.

I guess it applies to other restrictions as well.

**Comment by jaytasol** [comment]
Hi,

I want to do same thing, here is info...

Can anybody help me to know how can i handle exception, response file throwing exception in parse function. and it calls from send function of request. So i can not find way to handle this exception before before i call $xero->load('Accounting\Invoice')->where('Status', 'AUTHORISED')->execute();

I want to display message to user and redirect them to login page when this type of error occur.

Thanks

**Comment by jaytasol** [comment]
Hi there?

I am getting this error 
"UnauthorizedException in Response.php line 85: Token OEMHA5S5ADEIGZPCVOYXDGSVBA1XAA does not match an expected ACCESS token"

I have tried to handle this in my modal like this

  try {
        $request->send();
    } catch (Exception $e){
         echo($e->getCode());
         print_r($request->getResponse()->getOAuthResponse()); 
    }

But then also it is giving same error instead of display code in catch part. Can any one have idea how can i handle this directly in my modal? or i need to change core function of package? 

Thanks

**Comment by mhlavac** [comment]
@jaytasol your exception is not connected to parts of parameters being supported only by parts of Xero API.

I think the problem you have is from wrongly handled authorization, or your token is not valid anymore.

Unfortunately to show the warning/error in popup has to be done on your side. You can do it as you do it now, by catching the exception.

**Comment by jaytasol** [comment]
Hi,

As you told i have tried same code i wrote above but it was not working. Here is why that is not working. 

When we user send function of request.php, it calls parse function from response class which handle all exception so instead of going to my exception section it terminate function at parse function of response class. So i think there is any other way except to customizing code files to show message to users when some thing going wrong. 

Also if can can do handle it with this then it will be more then good. 
$xero->load('Accounting\Invoice')->where('Status', 'AUTHORISED')->execute();

But i can not fund a way to do this. 

Thanks

**Comment by mhlavac** [comment]
@jaytasol you mean customize provided example files?

**Comment by jaytasol** [comment]
No i mean to customize core file of package response.php/request.php. But in actual if i can do this in provided example file then it will be good, but when i am trying that it terminate my code before it throw exception in model file.

**Comment by calcinai** [comment]
@jaytasol - can you please open a new issue with a clear explains toon of what you're trying to do. You've completely detracted from the thread.

**Comment by jaytasol** [comment]
ok sure

**Comment by jaytasol** [comment]
Hi Michael,

I have open new thread #61 

Thanks,
Jay
