### ISSUE TITLE
Deleting an Invoice doesn't work?

### ISSUE THREAD

**Issue by FrankEBailey** [calcinai/xero-php#615]
I check for the existence of an Invoice, and if it exists, I want to delete it so I can recreate it. The Invoice, if it exists, has a status of DRAFT. So I'm using the below code to delete the Invoice, but despite it throwing no errors or exceptions, the Invoice retains its DRAFT status and is not deleted. Am I doing something wrong?

		$checkBill = $xero
			->load('Accounting\Invoice')
			->where('InvoiceNumber', $OrderNumber)
			->execute();
		
		if($checkBill[0]) {
			$bill = $checkBill[0];
			$guid = $bill->InvoiceID;
		};	
		
		$inv= $xero->loadByGUID('Accounting\Invoice', $guid);
		$inv->setStatus('DELETED');
		$inv->save();

**Comment by FrankEBailey** [comment]
False alarm

**Comment by edegaudenzi** [comment]
Hi Everyone,

I have exactly the same problem as FrankEBailey. Using the php-xero v2.0.1 I need to save a number of draft invoices and delete them immediately after. So far, I can see the new invoices in DRAFT, but they are not deleted. 
The code is something like:

`
$XeroApp->saveAll($arrXeroInvoices);

foreach ($arrXeroInvoices as $objXeroInvoice) {
    $objXeroInvoice->setStatus(INVOICE_STATUS_DELETED);
}

$response = $XeroApp->saveAll($arrXeroInvoices);
`

Something similar to this worked literally for years. Now $response contains an error for each of the invoices:

`
<invoice status="ERROR">
    <validationerrors>
        <validationerror>
            <message>One or more line items must be specified</message>
        </validationerror>
        <validationerror>
            <message>Invoice not of valid status for creation</message>
        </validationerror>
        <validationerror>
            <message>Invoice Type must be specified</message>
        </validationerror>
        <validationerror>
            <message>A Contact must be specified for this type of transaction</message>
        </validationerror>
    </validationerrors>
    <date>2020-03-25T00:00:00</date>
    <status>DELETED</status>
    <lineamounttypes>Exclusive</lineamounttypes>
    <subtotal>0.00</subtotal>
    <totaltax>0.00</totaltax>
    <total>0.00</total>
    <currencycode>GBP</currencycode>
    <invoiceid>00000000-0000-0000-0000-000000000000</invoiceid>
    <haserrors>true</haserrors>
</invoice>
`

Note that if you print the array after the loop and before the second saveAll(), everything is populated! InvoiceID, Status, Contact, Invoice Line etc...

I have already tried:
- Xero API Previer, from there it works
- clone $arrXeroInvoices 
- Create a brand new array of brand new objects
- in vendor\calcinai\xero-php\src\XeroPHP\Application.php, saveAll() decides whether to use PUT or POST depending on the GUID existence of the entity. Even this is correct: the function correctly set PUT at the first saveAll() and POST in the second.

Anything I am missing?

**Comment by calcinai** [comment]
@edegaudenzi You've done more thorough diagnostics than 99% of the issues here, thanks!  I'm sorry that I have no idea why it's not working, assuming that what you tested int he API previewer was the XML generated from the library? 

@FrankEBailey What did you do to resolve it?

**Comment by edegaudenzi** [comment]
Short story long: it's now perfectly working.

@calcinai You are a star. With just your comment, you pointed me exactly on the issue!

So, the issue was: 
in vendor\calcinai\xero-php\src\XeroPHP\Application.php::saveAll(), there is the following instruction: _$object_arrays[] = $object->toStringArray(true);_

That _TRUE_ is actually a $dirty_only = true, meaning that the XML will only be built on dirty Attributes (aka changed attributes)

Now, the solution to my previous example would be very easy:

$XeroApp->saveAll($arrXeroInvoices);

foreach ($arrXeroInvoices as $objXeroInvoice) {
**$objXeroInvoice->setDirty('InvoiceID');**
$objXeroInvoice->setStatus(INVOICE_STATUS_DELETED);
}

$response = $XeroApp->saveAll($arrXeroInvoices);

In this way the XML will also be built using InvoiceID, otherwise ignored because didn't change.

Discussion:
while the decision to force $dirty_only = true should maybe reported into the documentation somewhere, it might be beneficial to take the following consideration:
The code already knows if the SaveAll is going to be a PUT or a POST: $has_guid = true; decides it. 

So, why don't we insert the GUID in the XML by default, if present? In this way the functionality remains untouched and developers headache is gone! ;)

**Comment by calcinai** [comment]
@edegaudenzi there is absolutely no reason not to do what you're suggesting.  In fact, I think it's a great solution.
