### ISSUE TITLE
Does sendEmail() work with saveAll() ?

### ISSUE THREAD

**Issue by gleighfield** [calcinai/xero-php#616]
Is it possible via the API to not only save all my invoices being made with one API call but to tell it to email them also?

I'm creating 100+ invoices once a month, and hitting into API limits currently, would be great to have one call to not only create them (currently working just fine) but to email them also!

Maybe something like the below?

`$xero->saveAll($invoices)->sendEmail();`

Many thanks,

**Comment by timacdonald** [comment]
Unfortunately the Xero API (from what I can see) only allows sending one invoice per request.

See: https://developer.xero.com/documentation/api/invoices#email

I've have also wrestled with the api limits and I know many others have as well. There are 2 api limits imposed by Xero:

- Minute Limit: 60 calls in a rolling 60 second window
- Daily Limit: 5000 calls in a rolling 24 hour window

See: https://developer.xero.com/documentation/auth-and-limits/xero-api-limits

I found I used to hit the first limit, but on my apps never really hit the 5000 api calls per day limit. There are plenty of ways to handle this, but of course it all depends on your app and the infrastructure you have available.

Personally I'm working on Laravel applications so I can stagger the jobs over a period of time on a background queue, so that I don't go over the api limit. It would also be possible do a similar thing with a cron job and some database flags.

Due to the time based nature of dispatching requests to stay under the API limit, there isn't really anything the library itself can do without knowing your specific infrastructure.

Although I wouldn't recommend it, you _could_  set the PHP timeout to 30 minutes, and do a `sleep(2)` between requests. But then you've gotta work out how to handle failures and how you retry things etc.

**Comment by gleighfield** [comment]
Hi Tim,

Thanks for taking the time to get back to me - it's greatly appreciated.

Your comments mimic the research I've done in the interim. Which isn't ideal. Basically, we want to handle the invoice generation through our CRM, and use Xero to fulfil.

It seems every route I go down, I run into obstacles! All we're trying to do, is once a month, send out on brand invoices, with the PDF attached. Routes I've explored so far...

1.) Try to get around API limits, and use saveAll() - works, but the downside is, no email sent to customers.

2.) Use the save() method, handle emails outside, then the getPDF() method to attach the PDF tto the email and send (total of two api calls per invoice) however no link to pay online in the returned save the object.

**Comment by calcinai** [comment]
@gleighfield Have you tried contacting Xero directly? They might (at least functionally) have an idea on how to achieve this.

If it's possible with the API, we can make it work here

**Comment by gleighfield** [comment]
Hi @calcinai 

Tried them, all I got was a "not possible".

There are so many inconsistencies with their email sending methods. Sending a single through there UI works with HTML, sending bulk from their UI doesn't. Sending an email through their API doesn't, and also (as we found out yesterday) their invoice reminder emails arn't formatted either.

Such a shame thatt such a basic piece of HTML formatting isn't "supported"
