### ISSUE TITLE
Public app token does not match

### ISSUE THREAD

**Issue by jaroslawziolkowski** [calcinai/xero-php#89]
Hi,
After copy this example
https://github.com/calcinai/xero-php/blob/master/examples/public.php
when I receive answer from XERO
I see exception
```
 Token (token from oauth_token var) does not match an expected REQUEST token
``` 

I tried contact with xero but their support doesn't know why.

Do you know what can be wrong? My app in XERO is public.

**Comment by wildflower** [comment]
I don't know the exact answer but on line 28 you get a Token from Xero
and then you get another token from Xero after you've authorized your app to access your Xero account.

Maybe you are using the first Token on subsequent requests, rather than the 2nd one that comes back after you've authorized?

try doing some print_r or var_dumps to see which bits of code are running,

from memory - i ran into this about 2 weeks ago :
there isn't a key in this array called $oauth_response['expires'] - i can't remember what it's called but the value is 1800 (30 minutes in Seconds) so the test to see if your Session has expired won't work i.e if( now() > expired)

**Comment by calcinai** [comment]
@jaroslawziolkowski, did you get to the bottom of the issue?

**Comment by pshechko** [comment]
As I can see, the issue is still there. The token returned in the address line from the xero throws that exception as well
