### ISSUE TITLE
Contact addBankAccountDetail should be setBankAccountDetail

### ISSUE THREAD

**Issue by wildflower** [calcinai/xero-php#90]
There is an implied convention in the class where Strings are Set and Objects are Added.

I haven't noticed any other 'mistakes' ( using add instead of set) .
I can only find the one place where addBankAccountDetail is called/defined - in Contact.php

Changing it might break other people's code
I can make a Pull request

**Comment by calcinai** [comment]
The rule isn't anything to do with data type, it's if the property is an array or not.  Calling ```addXxx()``` multiple times keeps adding values, while ```setXxx()``` replaces them.

The problem is that it's being parsed as a plural, not a singular.  I can update this, but as you said, might break others' code. I'll Make a note in the version.
